facebook_ads:
  access_token: "your_facebook_access_token"
  ad_account_id: "your_facebook_ad_account_id"

google_ads:
  credentials_file: "path_to_google_credentials.json"
  client_id: "your_google_client_id"
  customer_id: "your_google_customer_id"

database:
  url: "jdbc:postgresql://localhost:5432/ads_database"
  user: "db_username"
  password: "db_password"